### ISSUE TITLE
Question: RightContent.razor should not be a component?

### ISSUE THREAD

**Issue by anddrzejb** [ant-design-blazor/pro-components#17]
I am having a problem justifying the `RightContent.razor` as a component. First it gave me a lot of trouble when I tried to use `AntDesign.Pro` full version. I will in steps describe what I did and what I noticed:
1. I created a new `AntDesign.MySite` project using command line `dotnet new antdesign --host=server --full` 
2. I found the template created files (among others) `Layouts/BasicLayout.razor` and `Components/GlobalHeader/RightContent.razor`. The latter is responsible for rendering of notification center, language picker and quick user actons. That `RightContent` component is consumed by `BasicLayout` component.
3. I wanted to do some customizations so I started changing the projects `RightContent.razor`. Whatever I was doing, no changes was reflected. 
4. Eventually I figured that the `RightContent` that was used was actually a component of **pro-components**. So I had to fully qualify the `RightContent` in `BasicLayout` like this: `<AntDesign.MySite.Components.RightContent />`
5. I cannot use F12 yet on razor components ([source](https://github.com/dotnet/aspnetcore/issues/21780)). Figuring out the source of my problem took me much more time than it should 😢 . 
6. It seems that `RightContent` does not expose enough api to be useful, so it has to be altered anyway.

It absolutely makes sense to keep `RightContent.razor` as a part of `AntDesign.Pro` template, but I can only see it being as an obstacle at this stage if it is used in `ProComponents`.
In my tests I transferred all the code related to `RightContent` to `AntDesign.Pro.Layout.Wasm` project to folder `Components/GlobalHeaders`. Running the example project works as before.

**Comment by yoli799480165** [comment]
Thank you for your comments. It makes sense to put the whole RightContent component into AntDesign.Pro project. That's what we're planning to do.

The changes of Components/GlobalHeader/RightContent.razor should be effective, maybe we need to do some testing to figure out what happened.

**Comment by anddrzejb** [comment]
I can do a PR for this, but this obviously requires also a PR in AntDesign.Pro - they would have to be tested and approved at the same time. And released at the same time as well I guess.
